title: "Homepages Widget SDK"
remote_theme: pmarsceill/just-the-docs
color_scheme: 'light-theme'
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/infor-logo.png"

# Aux links for the upper right navigation
aux_links:
  "Homepages Widget SDK on GitHub":
    - "//github.com/infor-cloud/homepages-widget-sdk"
