title: asdasdasdas
description: Homepages Widget SDK
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/Infor_TMLogo_RGB_1500px_72dpi_080512"

# Aux links for the upper right navigation
aux_links:
  "Homepages Widget SDK on GitHub":
    - "//github.com/infor-cloud/homepages-widget-sdk"

# Enable search
search_enabled: true

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true